
var noticia = [
  { id: 13, titulo: 'Professor João Moreira é palestrante convidado do PGSC',
    corpo: 'O Professor João Moreira, pesquisador na área de Serviços e Segurança Cibernética da Universidade de Twente, Holanda, foi convidado para proferir uma palestra para o PGSC. Em sua palestra, João Moreira abordou o tema Gerência de Dados FAIR (Findable, Accessible, Interoperable and Reusable), que suscita a criação de princípios e práticas que orientem a descoberta, o acesso, a integração e a reutilização da vasta quantidade de dados e informação gerada pela ciência. Os princípios FAIR são regulados por intermédio de protocolos que definem a interoperabilidade semântica básica dos conjuntos de dados, quando possível, usando-se padrões e protocolos comunitários já aprovados ou emergentes. Sua palestra pode ser vista no <a href="https://youtu.be/BP84Ty3szqQ" target="_blank">Youtube</a>.', arquivo: '',
    data: '20210113' },
  { id: 12, titulo: 'Resultado da Seleção Mestrado - 2021/1',
    corpo: 'O resultado do processo de seleção ao curso de Mestrado em Sistemas e Computação para 2021/1 foi divulgado pela Subdivisão de Cursos de Pós-graduação do IME (SD/1) e pode ser visto em <a href="http://www.ime.eb.mil.br/images/arquivos/admissao/pos-graduacao/2021/Relacao-dos-aprovados-2021.1.pdf" target="_blank">aqui</a>. O Programa felicita os selecionados e os espera receber na semana de matrículas para 2021/1 (de 22 a 26 Fev 2021).', arquivo: '',
    data: '20210113' },
  { id: 11, titulo: 'Projeto de egresso do PGSC apresentado no Ontobras 2020',
    corpo: 'O artigo "Critical Communications Scenarios Description based on Ontological Analysis" do aluno de doutorado Julio Cesar Tesolin, egresso do PGSC, com orientação da professora Maria Claudia Cavalcanti e co-autoria da professora Maria Luiza Campos (UFRJ) e do TC Davi Moura (CACTT-CPQD, EB), apresentado no Ontobras 2020 está disponível no <a href="https://youtu.be/17UEQ9FD_hs" target="_blank">Youtube</a>. O trabalho descreve o uso de Unified Foundational Ontology (UFO) no domínio de aplicação de comunicações críticas (p.ex. cenários militares).', arquivo: '',
    data: '20210113' },
 { id: 10, titulo: 'Trabalhos do PGSC se destacam e são premiados no XXVI Simpósio Brasileiro de Sistemas Multimídia e Web (WebMedia)',
    corpo: 'O artigo do aluno Flávio Matias da Silva, em co-autoria com Paulo Freire, Ronaldo Goldschmidt, Marcelo Pereira de Souza e Gustavo Plenamente (alunos de graduação, pós-graduação e docente da SE/9) foi premiado como o melhor artigo da Trilha Principal do 20o WebMedia. Além disso, o artigo da professora Maria Claudia Reis Cavalcanti, em co-autoria com Jean Gabriel Nguema Ngomo, Giseli Lopes e Maria Luiza Machado Campos recebeu menção honrosa na Trilha Principal do 20o WebMedia, por ter sido um dos três finalistas ao prêmio de melhor artigo.', arquivo: '',
    data: '20201204' },
  { id: 9, titulo: 'Aluna do PGSC recebe prêmio de terceiro melhor artigo do 17o Latin American Robotics Symposium',
    corpo: 'O artigo da aluna Alexandra Raibolt, em co-autoria com Alberto Angonese e Paulo Rosa foi premiado como Third Best Paper no 17o Latin American Robotics Symposium (LARS). O trabalho "Comparative Evaluation of Feature Descriptors Through Bag of Visual Features with Multilayer Perceptron on Embedded GPU System" é baseado no trabalho de mestrado da aluna, desenvolvido no Laboratório de Robótica.', arquivo: '',
    data: '20201113' },
  { id: 8, titulo: 'Aluno do PGSC recebe prêmio no Symposium on Virtual and Augmented Reality',
    corpo: 'O artigo do aluno Antonio Luiz Carlucio Doneda, em co-autoria com Jauvave Cavalcante de Oliveira foi premiado como melhor artigo na categoria Aplicação do SRV 2020. O trabalho "Helicopter Visual Signaling Simulation: integrating VR and ML into a Low-cost Solutions to optimize Brazilian Navy Training" é uma iniciativa de integração entre o PGSC e a Marinha como o desenvolvimento de um simulador para treinamento de pilotos de helicópteros.', arquivo: '',
    data: '20201110' },
  { id: 7, titulo: 'PRORROGAÇÃO do prazo para o Processo de Seleção ao curso de Mestrado do PGSC para 2021/1',
    corpo: 'O processo de seleção para o curso de Mestrado em Sistemas e Computaçao do PGSC para início do curso em 2021/1 <span style="font-weight:bold;color:red;">estendeu o prazo para recebimento de inscrições para o dia 10 Dez</span>. Maiores detalhes na página da SD/1 (<a href="http://www.ime.eb.mil.br/pt/civis-militares-da-reserva.html" target="_blank">veja aqui</a>). Venha estudar conosco!', arquivo: '',
    data: '20201106' },
  { id: 6, titulo: 'Processo de Seleção ao curso de Mestrado do PGSC para 2021/1',
    corpo: 'O processo de seleção para o curso de Mestrado em Sistemas e Computaçao do PGSC para início do curso em 2021/1 está <span style="font-weight:bold;color:red;">aberto</span>, recebendo inscrições de 26 Out a 06 Nov. Venha estudar conosco!', arquivo: '',
    data: '20201026' },
  { id: 5, titulo: 'Processo de Seleção ao curso de Mestrado do PGSC para 2020/3',
    corpo: 'O processo de seleção para o curso de Mestrado em Sistemas e Computaçao do PGSC para início do curso em 2020/3 está <span style="font-weight:bold;color:red;">suspenso</span>. O processo de seleção para início do curso em 2021/1 (inscrições de 26 Out a 06 Nov) <span style="font-weight:bold;color:red;">estará aberto</span> normalmente. Venha estudar conosco!', arquivo: '',
    data: '20200709' },
  { id: 4, titulo: 'Inscrições para Matrícula em Disciplina Isolada no PGSC em 2020/3',
    corpo: 'O PGSC não estará admitindo inscrições para matrícula em disciplina isolada de candidatos novos (que nunca realizaram disciplina isolada no curso em períodos anteriores) em 2020/3. Se você deseja ser aluno do curso de Mestrado em Sistemas e Computação do PGSC, o processo de seleção, para início do curso em 2021/1, estará aberto de 26 Out a 06 Nov.', arquivo: '',
    data: '20200709' },
  { id: 3, titulo: 'QTS para 2020/2',
    corpo: 'O QTS para 2020/2 já está disponível. Para saber como realizar a matrícula, veja <span style="font-weight:bold;">Procedimentos Acadêmicos</span>. O período de Matrícula em Disciplinas é de 08 a 12 JUN, conforme o Calendário Escolar <span style="font-weight:bold;">(ver Menu - Central de Conteúdos - Calendário Escolar)</span>. É preciso ter acesso à VNP do IME.', arquivo: 'QTS-2020-2_vfinal.pdf',
    data: '20200527' },
  { id: 2, titulo: 'Atualização do Calendário Escolar (PGEPesq IME)',
    corpo: 'O Calendário Escolar da Pós-graduação do IME foi alterado devido à pandemia do Coronavírus <span style="font-weight:bold;">(ver Menu - Central de Conteúdos - Calendário Escolar)</span>.', arquivo: '',
    data: '20200401' },
  { id: 1, titulo: 'QTS para 2020/1',
    corpo: 'O QTS para 2020/1 já está disponível <span style="font-weight:bold;">(ver Menu - Central de Conteúdos - QTS)</span>.', arquivo: '',
    data: '20200129' }
];
